[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.clangd]
command = "clangd"
args = [
  "--background-index",
  "--clang-tidy",
  "--completion-style=detailed",
  "--all-scopes-completion"
]

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "toml"
auto-format = true
